### ISSUE TITLE
Create typescript interfaces based on database diagram

### ISSUE THREAD

**Issue by angelroma** [hrodri02/tournaments-frontend#3]
We need to create typescript interfaces based on the following diagram:

https://app.diagrams.net/#G1kB4PZja_OPeplOAj8VcYQemdp_MDxRee#%7B%22pageId%22%3A%229f46799a-70d6-7492-0946-bef42562c5a5%22%7D

**Comment by hrodri02** [comment]
I created the interfaces based on the **updated** ER diagram.
